FROM hello-world
MAINTAINER David Flemström <dflemstr@spotify.com>

ARG IMAGE_VERSION
ARG ARG_WITH_SPACE
ARG ARG_WITH_PLUS

LABEL version=${IMAGE_VERSION}
LABEL arg_with_space=${ARG_WITH_SPACE}
LABEL arg_with_plus=${ARG_WITH_PLUS}
